import customtkinter as ctk
from tkinter import filedialog, messagebox
import socket
import os
import threading
from Caesar import *

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")


class FileTotalApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.title("FileTotal - AI File Scanner")
        self.geometry("700x650")
        self.configure(fg_color="#121212")  # רקע כהה מאוד לאפליקציה

        # כתובת השרת
        self.server_ip = '10.252.1.172'
        self.server_port = 5500
        self.key = 5
        self.cipher = Caesar(self.key)

        # יצירת קונטיינר ראשי עם עיצוב של "כרטיס"
        self.main_container = ctk.CTkFrame(self, fg_color="#1e1e1e", corner_radius=20, border_width=1,
                                           border_color="#333333")
        self.main_container.pack(expand=True, fill="both", padx=40, pady=50)

        # הצגת מסך ההעלאה כברירת מחדל
        self.show_upload_screen()

    def clear_screen(self):
        for widget in self.main_container.winfo_children():
            widget.destroy()

    # --- מסך 1: העלאה ---
    def show_upload_screen(self):
        self.clear_screen()

        # כותרת עם גופן מודרני יותר
        title = ctk.CTkLabel(self.main_container, text="FileTotal", font=("Segoe UI", 42, "bold"), text_color="#3B8ED0")
        title.pack(pady=(30, 10))

        subtitle = ctk.CTkLabel(self.main_container, text="AI-Powered Malware Scanner", font=("Segoe UI", 14),
                                text_color="#888888")
        subtitle.pack(pady=(0, 30))

        # אזור ה-Drop משופר
        self.drop_frame = ctk.CTkFrame(self.main_container, width=450, height=180,
                                       fg_color="#252525", border_width=2,
                                       border_color="#3B8ED0", corner_radius=15)
        self.drop_frame.pack(pady=10)
        self.drop_frame.pack_propagate(False)

        self.file_label = ctk.CTkLabel(self.drop_frame, text="Click the button to select", font=("Segoe UI", 13),
                                       text_color="#aaaaaa")
        self.file_label.pack(expand=True, pady=(20, 0))

        # כפתור בחירה מעוצב כ-Outline
        self.select_btn = ctk.CTkButton(self.drop_frame, text="Choose File", command=self.select_file,
                                        fg_color="transparent", border_width=2, border_color="#3B8ED0",
                                        hover_color="#1a3a5a")
        self.select_btn.pack(pady=20)

        # הודעת סטטוס
        self.status_label = ctk.CTkLabel(self.main_container, text="",
                                         font=("Segoe UI", 12, "italic"), text_color="#3B8ED0")
        self.status_label.pack(pady=10)

        # כפתור סריקה רחב ומרשים
        self.upload_btn = ctk.CTkButton(self.main_container, text="Upload & Scan",
                                        command=self.start_scan_thread,
                                        width=200, height=45, font=("Segoe UI", 15, "bold"),
                                        state="disabled", fg_color="#444444", hover_color="#1c8046")
        self.upload_btn.pack(pady=20)

    def select_file(self):
        file_path = filedialog.askopenfilename()
        if file_path:
            self.selected_path = file_path
            self.file_label.configure(text=os.path.basename(file_path), text_color="#3B8ED0", font=("Segoe UI", 15))
            self.upload_btn.configure(state="normal", fg_color="#27ae60")

    # --- מסך 2: תוצאות AI ---
    def show_result_screen(self, final_report=None):
        self.clear_screen()

        self.main_container.grid_columnconfigure(0, weight=1)
        self.main_container.grid_rowconfigure(2, weight=1)

        title = ctk.CTkLabel(self.main_container, text="Analysis Report", font=("Segoe UI", 32, "bold"),
                             text_color="#3B8ED0")
        title.grid(row=0, column=0, pady=(20, 5), sticky="n")

        subtitle = ctk.CTkLabel(self.main_container, text="Results generated by Gemini AI", font=("Segoe UI", 14),
                                text_color="#888888")
        subtitle.grid(row=1, column=0, pady=5, sticky="n")

        # תיבת טקסט עם רקע כהה יותר למראה מקצועי
        self.result_area = ctk.CTkTextbox(self.main_container, font=("Consolas", 13),
                                          fg_color="#161616", border_width=1, border_color="#333333")
        self.result_area.grid(row=2, column=0, padx=30, pady=15, sticky="nsew")

        if final_report:
            clean_report = final_report.replace("Scanning... (it may take some time, please stand by)", "").strip()
            self.result_area.insert("0.0", clean_report)
        self.result_area.configure(state="disabled")

        back_btn = ctk.CTkButton(self.main_container, text="Scan Another File", command=self.show_upload_screen,
                                 width=180, height=40, fg_color="#3B8ED0", hover_color="#2a6ca3", font = ("Segoe UI", 15, "bold"))
        back_btn.grid(row=3, column=0, pady=25, sticky="s")

    def animate_dots(self, count=0):
        # בדיקה 1: האם הווידג'ט בכלל קיים בזיכרון?
        try:
            if not self.status_label.winfo_exists():
                return
        except:
            return
        # בדיקה 2: האם אנחנו עדיין במצב עבודה?
        # (אם הטקסט בכפתור חזר להיות "Upload & Scan", סימן שהסריקה נגמרה)
        if self.upload_btn.cget("text") == "Upload & Scan":
            return
        dots = "." * (count % 4)
        # עדכון הטקסט בבטחה
        try:
            self.status_label.configure(
                text=f"Scanning{dots}",
                font=("Segoe UI", 15, "bold"),
                text_color="#d18b21"
            )
            # קריאה לסיבוב הבא
            self.after(500, lambda: self.animate_dots(count + 1))
        except:
            # אם קרתה שגיאה בזמן העדכון (למשל המסך נסגר בדיוק באותו רגע), פשוט נעצור
            return


    def start_scan_thread(self):
        self.upload_btn.configure(state="disabled", text="Sent",fg_color="#444444")
        self.select_btn.configure(state="disabled")
        self.animate_dots()


        threading.Thread(target=self.send_file_to_server, daemon=True).start()

    def send_file_to_server(self):
        client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            client_socket.connect((self.server_ip, self.server_port))
            file_name = os.path.basename(self.selected_path)
            file_size = os.path.getsize(self.selected_path)
            header = f"{file_name}|{file_size}\n"
            client_socket.send(header.encode('utf-8'))
            with open(self.selected_path, "rb") as f:
                while chunk := f.read(4096):
                    encrypted_chunk = self.cipher.caesar_cipher_bytes(chunk, self.key)
                    client_socket.sendall(encrypted_chunk)
            full_response = ""
            while True:
                data = client_socket.recv(4096)
                if not data: break
                full_response += data.decode('utf-8', errors='ignore')
            self.after(0, lambda: self.show_result_screen(full_response))
        except Exception as e:
            self.after(0, lambda: messagebox.showerror("Error", f"Connection failed: {e}"))
            self.after(0, self.show_upload_screen)
        finally:
            client_socket.close()


if __name__ == "__main__":
    app = FileTotalApp()
    app.mainloop()